<?php

namespace Main\CatalogBundle\Entity\Repository;

use Main\CatalogBundle\Entity\Product;
/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketItemRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getBasket($em,$user,$status){
        $basket =$em->getRepository('MainCatalogBundle:BasketItem')->findBy(array('user'=>$user,'status'=>0));    
        
        foreach($basket as $val){
           $product = $em->getRepository('MainCatalogBundle:Product')->getProduct($em,$val->getProduct()->getId(),$user);
           $val->setProduct($product);
         //  echo (int)$product->getIsPriceDiscount();
        }
        
        return $basket;
    }

    
}
