<?php

namespace Main\CatalogBundle\Entity\Repository;

use Main\CatalogBundle\Entity\ProductGroup;
/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUrl($id){
        
        $em = $this->getEntityManager();
        $group = $em->getRepository("MainCatalogBundle:ProductGroup")->findOneById($id);
        
        $txt = "";
        do{
            if(!$group->getHideAliasByURL()){
                $txt = $group->getAlias()."/".$txt;
            }    
            $group = $group->getParentGroup();
        }while($group);
        
        return substr($txt, 0, -1) ;
    }
    
    public function getGroupByAlias($param,$em){
        $data = $em->getRepository('MainCatalogBundle:ProductGroup')->findOneByAlias($param["alias"]);
        $url = "";      
        foreach($param as $key=>$val){
            if($key != "alias" && $key != "first"){
                $group = $em->getRepository('MainCatalogBundle:ProductGroup')->findOneByAlias($val);
                if (!$group) {
                    throw $this->createNotFoundException('The group does not exist');
                }
            }
        }
        return $data;
    }
    
}
