<?php

namespace Main\CatalogBundle\Entity\Repository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModifierRepository extends \Doctrine\ORM\EntityRepository
{
}
