<?php

namespace Main\CatalogBundle\Entity\Repository;

use Main\CatalogBundle\Entity\Product;
/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{

    
}
