<?php

namespace Main\PageBundle\Entity\Repository;
use Main\PageBundle\Entity\Page;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMenuData($arr,Page $page) 
    {
        $em = $this->getEntityManager();
        $menu = $em->getRepository("MainPageBundle:MenuItem")->findBy((array("menu"=>$arr["menu"],"parent"=>$arr["parent"])));
        
        if($menu){ 
            
            foreach($menu as $m){
                switch($m->getItemType()){
                    case 2:
                        $url = $page->getAlias()."/".$em->getRepository("MainCatalogBundle:ProductGroup")->getUrl($m->getLinkId());
                        break;
                    case 3:
                        $url = $m->getLink();
                        break;
                    case 4:
                        $url = "#";
                        break;    
                    default:
                        $url = "MenuItemRepositoryError";
                }
               
                $menu_result[] = array(
                                    "id"    =>$m->getId(),
                                    "title" =>$m->getTitle(),
                                    "link"  =>"/".$url
                );  
            }
        } else { $menu_result = false; }
        return $menu_result;
    }
}