<?php

namespace Main\PageBundle\Entity\Repository;

/**
 * PagePropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagePropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
