updater_index:
    path:     /
    defaults: { _controller: "MainNuberBundle:Updater:index" }
    methods:  GET

updater_show:
    path:     /{id}/show
    defaults: { _controller: "MainNuberBundle:Updater:show" }
    methods:  GET

updater_new:
    path:     /new
    defaults: { _controller: "MainNuberBundle:Updater:new" }
    methods:  [GET, POST]

updater_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainNuberBundle:Updater:edit" }
    methods:  [GET, POST]

updater_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainNuberBundle:Updater:delete" }
    methods:  DELETE
