services:
#    main_nuber.example:
#        class: Main\NuberBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    order_manager:
        class: Main\NuberBundle\Service\OrderManagerService
        arguments:
            em: "@doctrine.orm.entity_manager"
            um: "@update_manager"
    base_manager:
        class: Main\NuberBundle\Service\BaseManagerService
        arguments:
            em: "@doctrine.orm.entity_manager"
            sc: "@security.token_storage"
    collector_manager:
        class: Main\NuberBundle\Service\CollectorManagerService
        arguments:
            em: "@doctrine.orm.entity_manager"
            bm: "@base_manager"
    update_manager:
        class: Main\NuberBundle\Service\UpdateManagerService
        arguments:
            em: "@doctrine.orm.entity_manager"            
    uploader_manager:
        class: Main\NuberBundle\Service\UploaderManagerService
        arguments:
            em: "@doctrine.orm.entity_manager"  